[default]
#NOTIFICATION_TO=quux
#NOTIFICATION_FROM=quuux

#SMTP_USERNAME=foo
#SMTP_PASSWORD=bar
#SMTP_HOSTNAME=baz
SMTP_PORT=587
SMTP_STARTTLS=true
SMTP_SSL=false

#IMAP_USERNAME=foo
#IMAP_PASSWORD=bar
#IMAP_HOSTNAME=baz
IMAP_PORT=993
IMAP_SSL=true
IMAP_DEBUG=false
